# Status bar
StatusBar=Hidden
# Simulate key release
SimulateKeyRelease=False
# Delay of simulated key release in milliseconds
SimulateKeyReleaseDelay=100
# Monitor Pasteboard
MonitorPasteboard=False
# Remove tracking parameters
RemoveTrackingParameters=True
# Poll Pasteboard interval (s)
PollPasteboardInterval=2

[AppDefaultIM]
0="{\"appPath\":\"\\/Applications\\/Lark.app\\/\",\"imName\":\"shuangpin\",\"appId\":\"com.electron.lark\"}"
1="{\"appId\":\"com.mitchellh.ghostty\",\"appPath\":\"\\/Applications\\/Ghostty.app\\/\",\"imName\":\"keyboard-us\"}"
2="{\"imName\":\"keyboard-us\",\"appPath\":\"\\/Applications\\/Zed.app\\/\",\"appId\":\"dev.zed.Zed\"}"

[VimMode]
0=org.vim.MacVim

