# Status bar
StatusBar=Menu
# Simulate key release
SimulateKeyRelease=False
# Delay of simulated key release in milliseconds
SimulateKeyReleaseDelay=100
# Monitor Pasteboard
MonitorPasteboard=False
# Remove tracking parameters
RemoveTrackingParameters=True
# Poll Pasteboard interval (s)
PollPasteboardInterval=2

[AppDefaultIM]
0="{\"appId\":\"dev.zed.Zed\",\"imName\":\"keyboard-us\",\"appPath\":\"\\/Applications\\/Zed.app\\/\"}"
1="{\"appId\":\"com.mitchellh.ghostty\",\"appPath\":\"\\/Applications\\/Ghostty.app\\/\",\"imName\":\"keyboard-us\"}"

[VimMode]
0=org.vim.MacVim

