# Reference: https://github.com/i3/i3/blob/next/etc/config

enable-normalization-flatten-containers = false
enable-normalization-opposite-orientation-for-nested-containers = false
default-root-container-layout = 'accordion'
default-root-container-orientation = 'vertical'

[mode.main.binding]
alt-shift-enter = 'exec-and-forget open -n /Applications/Alacritty.app'
alt-shift-c = 'exec-and-forget open -n /Applications/CotEditor.app'

alt-shift-h = 'focus left'
alt-shift-j = 'focus down'
alt-shift-k = 'focus up'
alt-shift-l = 'focus right'

alt-shift-s = 'layout v_accordion'
alt-shift-v = 'layout h_tiles'

alt-shift-ctrl-h = 'move left'
alt-shift-ctrl-j = 'move down'
alt-shift-ctrl-k = 'move up'
alt-shift-ctrl-l = 'move right'

# Not supported, because this command is redundant in AeroSpace mental model.
# See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
#alt-space = 'focus toggle_tiling_floating'

# `focus parent`/`focus child` are not yet supported, and it's not clear whether they
# should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
# alt-a = 'focus parent'

alt-shift-1 = 'workspace 1'
alt-shift-2 = 'workspace 2'
alt-shift-3 = 'workspace 3'
alt-shift-4 = 'workspace 4'
alt-shift-5 = 'workspace 5'
alt-shift-6 = 'workspace 6'
alt-shift-7 = 'workspace 7'
alt-shift-8 = 'workspace 8'
alt-shift-9 = 'workspace 9'
alt-shift-0 = 'workspace 10'

alt-shift-ctrl-1 = 'move-node-to-workspace 1'
alt-shift-ctrl-2 = 'move-node-to-workspace 2'
alt-shift-ctrl-3 = 'move-node-to-workspace 3'
alt-shift-ctrl-4 = 'move-node-to-workspace 4'
alt-shift-ctrl-5 = 'move-node-to-workspace 5'
alt-shift-ctrl-6 = 'move-node-to-workspace 6'
alt-shift-ctrl-7 = 'move-node-to-workspace 7'
alt-shift-ctrl-8 = 'move-node-to-workspace 8'
alt-shift-ctrl-9 = 'move-node-to-workspace 9'
alt-shift-ctrl-0 = 'move-node-to-workspace 10'

alt-shift-r = 'mode resize'

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'

[workspace-to-monitor-force-assignment]
1 = '1'
3 = '1'
2 = '2'
4 = '2'

[[on-window-detected]]
if.app-id = 'org.alacritty'
run = 'move-node-to-workspace 1'

[[on-window-detected]]
if.app-id = 'net.electron.lark'
run = 'move-node-to-workspace 4'

[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode'
run = 'move-node-to-workspace 3'

[[on-window-detected]]
if.app-id = 'com.coteditor.CotEditor'
run = 'move-node-to-workspace 9'

[[on-window-detected]]
if.app-id = 'com.proxyman.NSProxy'
run = 'move-node-to-workspace 3'

[[on-window-detected]]
if.app-name-regex-substring = 'NextChat'
run = 'move-node-to-workspace 10'
