#!/usr/bin/sh

cd "$HOME"

echo "Init submodules"
yadm submodule update --recursive --init

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then
  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  fi
fi

if [ "$system_type" = "Linux" ]; then
  if command -v pacman >/dev/null 2>&1; then
    echo "Update pacman"
    sudo pacman -Syu --noconfirm
    sudo pacman -S bash-completion base-devel difftastic gdb caddy mise atuin tldr tealdeer vim bat ripgrep fzf glow broot lf tmux --noconfirm
  fi
fi
