#!/usr/bin/sh

cd "$HOME"

echo "Init submodules"
yadm submodule update --recursive --init

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then
  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Install homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  fi
fi

if [ "$system_type" = "Linux" ]; then
  if command -v pacman >/dev/null 2>&1; then
    echo "Update pacman"
    sudo pacman -Syu --noconfirm
    sudo pacman -S bash-completion base-devel difftastic gdb caddy mise atuin tldr tealdeer vim bat ripgrep fzf glow broot lf tmux fd --noconfirm
  fi

  mise install
fi

if command -v vim >/dev/null 2>&1; then
  echo "Install vim plugins"
  vim '+PlugUpdate' '+qall'
fi

if [ ! -d "$HOME/.tmux/plugins/tpm" ]; then
  echo "Install tmux"
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
fi

