.TH mise 1
.SH 启用
.TP
.BI activate
输出在当前 shell 启用的 script 内容
.TP
.BI bin-paths
列出所有当前激活工具的路径
.TP
.BI deactivate
反激活当前 shell
.TP
.BI completion
输出补全 script
.TP
.BI env
仅输出需要启用所需的 env
.TP
.BI shell
在当前 shell 启用指定工具
.TP
.BI exec
在激活状态下执行命令
.SH mise 本体管理
.TP
.BI doctor
排障
.TP
.BI implode
完全卸载
.TP
.BI self-update
更新
.TP
.BI settings
管理设置
.TP
.BI version
版本号
.SH 配置文件管理
.TP
.BI config
配置管理
.TP
.BI trust
信任配置
.TP
.BI fmt
格式化配置
.TP
.BI sync
同步其他版本管理配置到 mise
.TP
.BI set
设置配置中环境变量
.TP
.BI unset
移除配置中环境变量
.TP
.BI use
安装工具，添加到配置
.TP
.BI unuse
从配置中移除工具
.SH 工具安装、升级、卸载
.TP
.BI install
安装工具
.TP
.BI install-into
安装工具到指定位置
.TP
.BI alias
工具别名管理
.TP
.BI cache
安装缓存管理
.TP
.BI link
符号链接一个工具到 mise
.TP
.BI prune
删除未使用的工具
.TP
.BI upgrade
升级非最新工具
.TP
.BI test-tool
测试工具安装过程
.TP
.BI reshims
在 .local/share/mise/shims/ 目录下重建所有工具、所有版本暴露出的可执行文件
.SH 各种信息查看
.TP
.BI ls
列出已安装
.TP
.BI ls-remote
列出远程列表
.TP
.BI outdated
列出本地非最新
.TP
.BI lastest
列出最新
.TP
.BI plugins
列出已安装插件（部分工具需要额外插件才能安装）
.TP
.BI backends
列出所有 backend
.TP
.BI registry
对于一个工具，展示其完整 name（使用的 backend、plugin）
.TP
.BI tool
列出一个工具的完整信息
.TP
.BI where
列出一个工具的安装位置
.TP
.BI which
列出一个工具的 bin 位置
.SH task
.TP
.BI run
执行 task
.TP
.BI tasks
task 管理
.TP
.BI watch
监听执行
