import = ["~/.config/alacritty/papercolor_light.toml", "~/.config/alacritty/local.toml"]

[keyboard]
bindings = [
  { key = "`", mods = "Command", chars = "\u001B`" },
  { key = "f", mods = "Command", chars = "\u001Bf" },
  { key = "b", mods = "Command", chars = "\u001Bb" },
]

