[window]
option_as_alt = "Both"

[keyboard]
bindings = [
  # Command as Meta
  # { key = "a", mods = "Command", chars = "\u001Ba" },
  # { key = "b", mods = "Command", chars = "\u001Bb" },
  # { key = "c", mods = "Command", chars = "\u001Bc" },
  # { key = "d", mods = "Command", chars = "\u001Bd" },
  # { key = "e", mods = "Command", chars = "\u001Be" },
  # { key = "f", mods = "Command", chars = "\u001Bf" },
  # { key = "g", mods = "Command", chars = "\u001Bg" },
  # { key = "h", mods = "Command", chars = "\u001Bh" },
  # { key = "i", mods = "Command", chars = "\u001Bi" },
  # { key = "j", mods = "Command", chars = "\u001Bj" },
  # { key = "k", mods = "Command", chars = "\u001Bk" },
  # { key = "l", mods = "Command", chars = "\u001Bl" },
  # { key = "m", mods = "Command", chars = "\u001Bm" },
  # { key = "n", mods = "Command", chars = "\u001Bn" },
  # { key = "o", mods = "Command", chars = "\u001Bo" },
  # { key = "p", mods = "Command", chars = "\u001Bp" },
  # { key = "q", mods = "Command", chars = "\u001Bq" },
  # { key = "r", mods = "Command", chars = "\u001Br" },
  # { key = "s", mods = "Command", chars = "\u001Bs" },
  # { key = "t", mods = "Command", chars = "\u001Bt" },
  # { key = "u", mods = "Command", chars = "\u001Bu" },
  # { key = "v", mods = "Command", chars = "\u001Bv" },
  # { key = "x", mods = "Command", chars = "\u001Bx" },
  # { key = "y", mods = "Command", chars = "\u001By" },
  # { key = "z", mods = "Command", chars = "\u001Bz" },
  { key = "1", mods = "Command", chars = "\u001B1" },
  { key = "2", mods = "Command", chars = "\u001B2" },
  { key = "3", mods = "Command", chars = "\u001B3" },
  { key = "4", mods = "Command", chars = "\u001B4" },
  { key = "5", mods = "Command", chars = "\u001B5" },
  { key = "6", mods = "Command", chars = "\u001B6" },
  { key = "7", mods = "Command", chars = "\u001B7" },
  { key = "8", mods = "Command", chars = "\u001B8" },
  { key = "9", mods = "Command", chars = "\u001B9" },
  { key = "0", mods = "Command", chars = "\u001B0" },
  { key = "`", mods = "Command", chars = "\u001B`" },
  # { key = ".", mods = "Command", chars = "\u001B." },
  # { key = "Enter", mods = "Command", chars = "\u001B\u000D" },
  # { key = "Backspace", mods = "Command", chars = "\u001B\u007F" },

  # Other
  # { key = "(", mods = "Command|Shift", chars = "\u001B(" },
  # { key = ")", mods = "Command|Shift", chars = "\u001B)" },
  # { key = "n", mods = "Command|Option", action = "CreateNewWindow" },
  # { key = "c", mods = "Command|Option", action = "Copy" },
  # { key = "v", mods = "Command|Option", action = "Paste" },
]

[general]
import = ["~/.config/alacritty/onehalflight.toml", "~/.config/alacritty/local.toml"]

