import = ["~/.config/alacritty/papercolor_light.toml", "~/.config/alacritty/local.toml"]

[keyboard]
bindings = [
  { key = "`", mods = "Command", chars = "\u001B`" },
  { key = "f", mods = "Command", chars = "\u001Bf" },
  { key = "g", mods = "Command", chars = "\u001Bg" },
  { key = ".", mods = "Command", chars = "\u001B." },
  { key = "b", mods = "Command", chars = "\u001Bb" },
  { key = "1", mods = "Command", chars = "\u001B1" },
  { key = "2", mods = "Command", chars = "\u001B2" },
  { key = "3", mods = "Command", chars = "\u001B3" },
  { key = "4", mods = "Command", chars = "\u001B4" },
  { key = "5", mods = "Command", chars = "\u001B5" },
  { key = "6", mods = "Command", chars = "\u001B6" },
  { key = "7", mods = "Command", chars = "\u001B7" },
  { key = "8", mods = "Command", chars = "\u001B8" },
  { key = "9", mods = "Command", chars = "\u001B9" },
  { key = "0", mods = "Command", chars = "\u001B0" },
]

