[colors.normal]
black = "0xeeeeee"   #30
red = "0xBC1c1c"     #31
green = "0x388e3c"   #32
yellow = "0xf57f17"  #33
blue = "0x1565c0"    #34
magenta = "0xd81b60" #35
cyan = "0x00838f"    #36
white = "0x444444"   #37

[colors.bright]
black = "0x616161"   #90
red = "0xF44336"     #91
green = "0x8bc34a"   #92
yellow = "0xfbc02d"  #93
blue = "0x1e88e5"    #94
magenta = "0xf06292" #95
cyan = "0x00acc1"    #96
white = "0x212121"   #97

[colors.cursor]
cursor = "0x444444"
text = "0xeeeeee"

[colors.primary]
background = "0xeeeeee"
foreground = "0x444444"

