#!/usr/bin/env bash
#
# This hook includes three examples. The first one removes the
# "# Please enter the commit message..." help message.
#
# The second includes the output of "git diff --name-status -r"
# into the message, just before the "git status" output.  It is
# commented because it doesn't cope with --amend or with squashed
# commits.
#
# The third example adds a Signed-off-by line to the message, that can
# still be edited.  This is rarely a good idea.

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2
SHA1=$3

if [ "$COMMIT_SOURCE" = "message"]; then
  exit 0
fi

git log --decorate --oneline --graph -n 10 | sed 's/^/# /' >> $COMMIT_MSG_FILE
