[tools]
python = "3.11.9"
node = "20"
deno = "latest"
go = "1.24"
"npm:prettier" = "latest"
"npm:@antfu/ni" = "latest"
java = "21"
dotnet = "latest"
rust = "1.87.0"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node"]
