[tools]
python = "3.11.9"
node = "20"
deno = "latest"
go = "1.24"
usage = "2.0.0"
"npm:prettier" = "latest"
rust = "1.85.0"
"npm:@antfu/ni" = "latest"
java = "21"
dotnet = "latest"

[settings]
experimental = true
